name: whatsapp_status_downloader_2025
description: A Flutter app to download WhatsApp status images and videos.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.0.14
  gallery_saver: ^2.3.2
  video_player: ^2.7.0
  file_picker: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
