name: Flutter Android CI

on:
  push:
    branches:
      - main # or 'master' - specify your primary branch here

jobs:
  build:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2 # Action to set up Flutter environment
        with:
          flutter-version: '3.x' # Specify a recent Flutter version, e.g., '3.19.6' or '3.x' for latest 3.x
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze code (optional but recommended)
        run: flutter analyze

      - name: Run tests (optional but recommended)
        run: flutter test

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release # Builds the Android App Bundle for release

      - name: Upload Android App Bundle artifact
        uses: actions/upload-artifact@v4 # Action to upload build output
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      # If you prefer APK:
      # - name: Build Android APK
      #   run: flutter build apk --release
      # - name: Upload Android APK artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk
